// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOloxyzi2_L-J_ACwwfoV3V9Q5XGZpL_s',
    appId: '1:393808832863:web:d9953ec4133e4e8a13eeea',
    messagingSenderId: '393808832863',
    projectId: 'my-new-app-eadc8',
    authDomain: 'my-new-app-eadc8.firebaseapp.com',
    storageBucket: 'my-new-app-eadc8.appspot.com',
    measurementId: 'G-W0KRPN3Y30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPcRGRNcSGhxEbtmiqmguqFRcmET5aKPE',
    appId: '1:393808832863:android:628d096daf08e64713eeea',
    messagingSenderId: '393808832863',
    projectId: 'my-new-app-eadc8',
    storageBucket: 'my-new-app-eadc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-WDh3bJg__cOoIQgY_QM3kRTTeaS3gSo',
    appId: '1:393808832863:ios:5d0ab00b81b1935713eeea',
    messagingSenderId: '393808832863',
    projectId: 'my-new-app-eadc8',
    storageBucket: 'my-new-app-eadc8.appspot.com',
    iosBundleId: 'com.example.bankApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-WDh3bJg__cOoIQgY_QM3kRTTeaS3gSo',
    appId: '1:393808832863:ios:46373b2634694dd013eeea',
    messagingSenderId: '393808832863',
    projectId: 'my-new-app-eadc8',
    storageBucket: 'my-new-app-eadc8.appspot.com',
    iosBundleId: 'com.example.bankApp2.RunnerTests',
  );
}
